version: '3.8'

services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: albertt1001
      POSTGRES_PASSWORD: albertt1001
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./certs:/certs:ro
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: albertt1001
      DB_PASSWORD: albertt1001
      DB_NAME: mydatabase
      DB_CERT: /certs/server.crt


  frontend:
    image: nginx:stable
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata: